name: new release
on:
  release:
    types: [created]
jobs:
  publish-ngaox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: gh-pages
    # Setup .npmrc file to publish to npm
    - uses: actions/setup-node@v2
      with:
        registry-url: 'https://registry.npmjs.org'

    - name: publish ngaox
      run: |
        cd ngaox
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: publish ngaox-design
      run: |
        cd ngaox-design
        npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}